// Plain-language class learning overview generated by Coach AI.
// Returns a short summary in Italian: difficulties + concrete suggestions.
// NO percentages, NO technical scores in the response.

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { classId } = await req.json();
    if (!classId) {
      return new Response(JSON.stringify({ error: "classId mancante" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const sb = createClient(supabaseUrl, serviceKey);

    // Pull class context
    const { data: classe } = await sb.from("classi").select("*").eq("id", classId).maybeSingle();
    const subject = classe?.materia || "le materie della classe";

    // Pull recent assignment results to extract topic-level error signals
    const { data: assignments } = await sb
      .from("teacher_assignments").select("id, title, subject")
      .eq("class_id", classId)
      .order("assigned_at", { ascending: false })
      .limit(20);
    const aIds = (assignments || []).map((a: any) => a.id);

    let errorTopics: Record<string, number> = {};
    let totalCompleted = 0;
    let totalAssigned = 0;
    // Skip technical / placeholder keys that should never reach the teacher.
    const TECHNICAL_KEYS = new Set([
      "common_errors", "errors", "error", "summary", "score", "metric",
      "rate", "percent", "percentage", "total", "count", "n/a", "na", "null",
      "undefined", "unknown", "generic",
    ]);
    const isTechnicalKey = (k: string) => {
      const low = k.trim().toLowerCase();
      if (!low) return true;
      if (TECHNICAL_KEYS.has(low)) return true;
      if (/^[0-9_\-:.]+$/.test(low)) return true;
      return false;
    };
    if (aIds.length > 0) {
      const { data: results } = await sb
        .from("assignment_results").select("status, errors_summary")
        .in("assignment_id", aIds);
      (results || []).forEach((r: any) => {
        totalAssigned++;
        if (r.status === "completed") totalCompleted++;
        const es = r.errors_summary;
        if (es && typeof es === "object") {
          Object.entries(es).forEach(([topic, count]: [string, any]) => {
            if (isTechnicalKey(topic)) return;
            // If value is array of strings, treat each as a topic name
            if (Array.isArray(count)) {
              count.forEach((t: any) => {
                if (typeof t === "string" && !isTechnicalKey(t)) {
                  errorTopics[t] = (errorTopics[t] || 0) + 1;
                }
              });
              return;
            }
            const c = typeof count === "number" ? count : 1;
            errorTopics[topic] = (errorTopics[topic] || 0) + c;
          });
        }
      });
    }

    const topErrors = Object.entries(errorTopics)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 5)
      .map(([t, c]) => ({ topic: t, count: c }));

    // Build a compact context for the AI
    const completionRatio = totalAssigned > 0 ? Math.round((totalCompleted / totalAssigned) * 100) : null;
    const completionLabel = completionRatio == null
      ? "non ci sono ancora abbastanza dati di consegna"
      : completionRatio >= 80
        ? "la maggior parte degli studenti consegna i compiti"
        : completionRatio >= 50
          ? "circa metà degli studenti consegna i compiti"
          : "molti studenti non stanno consegnando i compiti";

    const errorsBlock = topErrors.length > 0
      ? topErrors.map(e => `- "${e.topic}" (errore ricorrente)`).join("\n")
      : "- nessun argomento critico chiaro al momento";

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      // Fallback deterministic summary
      const summary = topErrors.length > 0
        ? `La classe sta lavorando su ${subject}. Sono emerse alcune difficoltà ricorrenti su: ${topErrors.map(e => `"${e.topic}"`).join(", ")}. Inoltre ${completionLabel}.`
        : `La classe sta lavorando su ${subject}. Per ora non emergono difficoltà rilevanti e ${completionLabel}.`;
      const suggestions = topErrors.length > 0
        ? [
            `Dedica una breve attività di ripasso su "${topErrors[0].topic}" all'inizio della prossima lezione.`,
            "Forma piccoli gruppi misti dove gli studenti più sicuri spiegano ai compagni in difficoltà.",
            "Proponi un esercizio guidato passo passo per consolidare i concetti meno chiari.",
          ]
        : [
            "Continua con il ritmo attuale, è equilibrato.",
            "Considera un'attività di approfondimento per stimolare gli studenti più avanti.",
          ];
      return new Response(JSON.stringify({ summary, suggestions, source: "fallback" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const systemPrompt = `Sei il Coach AI di SarAI. Devi scrivere a un docente una sintesi breve, in italiano semplice e umano, dello stato di apprendimento della sua classe.
REGOLE:
- NON usare percentuali, punteggi numerici o termini tecnici (niente "score", "metric", "rate", "%").
- Usa un tono collegiale, concreto, max 3-4 frasi per la sintesi.
- I suggerimenti devono essere azioni didattiche concrete, max 3, ognuno in una frase.
- NON inventare nomi di studenti.
- Rispondi SOLO con JSON valido nello schema richiesto.

[PRINCIPIO DEL RICONOSCIMENTO — obbligatorio]
Ogni volta che descrivi la classe o nomini studenti, segui la struttura:
  1. RICONOSCIMENTO — cosa la classe STA facendo, provando, mostrando
  2. OSTACOLO       — la difficoltà specifica, nominata senza giudizio
  3. AZIONE         — un suggerimento concreto e immediato
MAI aprire con un deficit ("X studenti non consolidano", "Rendimento basso").
SEMPRE aprire con quello che la classe sta facendo, poi l'ostacolo.
ESEMPIO ❌: "4 studenti non stanno consolidando i decimali."
ESEMPIO ✅: "La classe sta lavorando, ma 4 studenti hanno incontrato un blocco preciso sui decimali — vale la pena raccoglierlo."
Tono di un collega fidato che vede sia impegno sia fatica, mai un report di fallimenti.`;

    const userPrompt = `Materia: ${subject}
Stato consegne: ${completionLabel}
Difficoltà ricorrenti rilevate dalle attività:
${errorsBlock}

Scrivi una sintesi (campo "summary") di 2-3 frasi e una lista di 2-3 suggerimenti pratici (campo "suggestions").`;

    const aiRes = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        tools: [{
          type: "function",
          function: {
            name: "report_class",
            description: "Sintesi e suggerimenti per il docente",
            parameters: {
              type: "object",
              properties: {
                summary: { type: "string" },
                suggestions: { type: "array", items: { type: "string" } },
              },
              required: ["summary", "suggestions"],
              additionalProperties: false,
            },
          },
        }],
        tool_choice: { type: "function", function: { name: "report_class" } },
      }),
    });

    if (!aiRes.ok) {
      const t = await aiRes.text();
      console.error("AI error", aiRes.status, t);
      // Fallback
      return new Response(JSON.stringify({
        summary: `La classe sta lavorando su ${subject}. ${completionLabel}.`,
        suggestions: topErrors.length > 0
          ? [`Riprendi insieme l'argomento "${topErrors[0].topic}" con un esempio guidato.`]
          : ["Procedi con il programma, la classe sembra in linea."],
        source: "fallback",
      }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const data = await aiRes.json();
    const toolCall = data.choices?.[0]?.message?.tool_calls?.[0];
    let parsed: any = { summary: "", suggestions: [] };
    if (toolCall?.function?.arguments) {
      try { parsed = JSON.parse(toolCall.function.arguments); } catch {}
    }

    return new Response(JSON.stringify({
      summary: parsed.summary || `La classe sta lavorando su ${subject}. ${completionLabel}.`,
      suggestions: Array.isArray(parsed.suggestions) ? parsed.suggestions.slice(0, 3) : [],
      source: "ai",
    }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e) {
    console.error("class-learning-summary error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
