// Plain-language class learning overview generated by Coach AI.
// Returns:
//  - summary + suggestions (legacy fallback)
//  - card1..card4: 4 actionable cards (apprendimento / metodo / clima / studente prioritario)
// NO percentages, NO technical scores in human-facing text.

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { classId } = await req.json();
    if (!classId) {
      return new Response(JSON.stringify({ error: "classId mancante" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const sb = createClient(supabaseUrl, serviceKey);

    // ── Class context ──
    const { data: classe } = await sb.from("classi").select("*").eq("id", classId).maybeSingle();
    const subject = classe?.materia || "le materie della classe";
    const className = classe?.nome || "la classe";

    // ── Recent assignments + results ──
    const { data: assignments } = await sb
      .from("teacher_assignments").select("id, title, subject")
      .eq("class_id", classId)
      .order("assigned_at", { ascending: false })
      .limit(20);
    const aIds = (assignments || []).map((a: any) => a.id);

    let errorTopics: Record<string, number> = {};
    let totalCompleted = 0;
    let totalAssigned = 0;
    let scoreSum = 0;
    let scoreCount = 0;
    const studentScoreAgg: Record<string, { sum: number; n: number; missed: number }> = {};

    const TECHNICAL_KEYS = new Set([
      "common_errors", "errors", "error", "summary", "score", "metric",
      "rate", "percent", "percentage", "total", "count", "n/a", "na", "null",
      "undefined", "unknown", "generic",
    ]);
    const isTechnicalKey = (k: string) => {
      const low = k.trim().toLowerCase();
      if (!low) return true;
      if (TECHNICAL_KEYS.has(low)) return true;
      if (/^[0-9_\-:.]+$/.test(low)) return true;
      return false;
    };

    if (aIds.length > 0) {
      const { data: results } = await sb
        .from("assignment_results").select("student_id, status, errors_summary, score")
        .in("assignment_id", aIds);
      (results || []).forEach((r: any) => {
        totalAssigned++;
        if (r.status === "completed") totalCompleted++;
        if (typeof r.score === "number") {
          scoreSum += r.score;
          scoreCount++;
        }
        // per-student aggregation
        const sid = r.student_id;
        if (sid) {
          if (!studentScoreAgg[sid]) studentScoreAgg[sid] = { sum: 0, n: 0, missed: 0 };
          if (typeof r.score === "number") {
            studentScoreAgg[sid].sum += r.score;
            studentScoreAgg[sid].n++;
          }
          if (r.status !== "completed") studentScoreAgg[sid].missed++;
        }

        const es = r.errors_summary;
        if (es && typeof es === "object") {
          Object.entries(es).forEach(([topic, count]: [string, any]) => {
            if (isTechnicalKey(topic)) return;
            if (Array.isArray(count)) {
              count.forEach((t: any) => {
                if (typeof t === "string" && !isTechnicalKey(t)) {
                  errorTopics[t] = (errorTopics[t] || 0) + 1;
                }
              });
              return;
            }
            const c = typeof count === "number" ? count : 1;
            errorTopics[topic] = (errorTopics[topic] || 0) + c;
          });
        }
      });
    }

    const topErrors = Object.entries(errorTopics)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 5)
      .map(([t, c]) => ({ topic: t, count: c }));

    const argomentoCritico = topErrors[0]?.topic || null;
    const completionRatio = totalAssigned > 0 ? Math.round((totalCompleted / totalAssigned) * 100) : null;
    const avgScore = scoreCount > 0 ? Math.round(scoreSum / scoreCount) : null;

    const completionLabel = completionRatio == null
      ? "non ci sono ancora abbastanza dati di consegna"
      : completionRatio >= 80
        ? "la maggior parte degli studenti consegna le attività"
        : completionRatio >= 50
          ? "circa metà degli studenti consegna le attività"
          : "molti studenti non stanno consegnando le attività";

    // ── Enrolled students + emotional signals (mood_streak >= 5) ──
    const { data: enrollments } = await sb
      .from("class_enrollments")
      .select("student_id")
      .eq("class_id", classId)
      .eq("status", "active");
    const studentUserIds = (enrollments || []).map((e: any) => e.student_id);
    const totalStudents = studentUserIds.length;

    let nSegnaliEmotivi = 0;
    let activeStudents = 0;
    const profileByParent: Record<string, any> = {};

    if (studentUserIds.length > 0) {
      const { data: profiles } = await sb
        .from("child_profiles")
        .select("id, parent_id, name, last_name, teacher_insights_consent")
        .in("parent_id", studentUserIds)
        .eq("teacher_insights_consent", true);

      const profileIds = (profiles || []).map((p: any) => p.id);
      (profiles || []).forEach((p: any) => { profileByParent[p.parent_id] = p; });

      if (profileIds.length > 0) {
        const { data: prefs } = await sb
          .from("user_preferences")
          .select("profile_id, mood_streak")
          .in("profile_id", profileIds);
        (prefs || []).forEach((p: any) => {
          if ((p.mood_streak || 0) >= 5) nSegnaliEmotivi++;
        });
      }

      // active = at least one assignment_result (completed or not) in window
      const activeSet = new Set<string>();
      Object.keys(studentScoreAgg).forEach(s => activeSet.add(s));
      activeStudents = activeSet.size;
    }

    // ── Studente prioritario ──
    // Lower avg score + more missed = higher priority
    let studentePrioritario: { user_id: string; name: string; avg: number | null; missed: number } | null = null;
    Object.entries(studentScoreAgg).forEach(([sid, agg]) => {
      const avg = agg.n > 0 ? agg.sum / agg.n : null;
      const candidate = { user_id: sid, name: profileByParent[sid]?.name || "Studente", avg, missed: agg.missed };
      if (!studentePrioritario) {
        studentePrioritario = candidate;
        return;
      }
      const curScore = (studentePrioritario.avg ?? 100) - studentePrioritario.missed * 5;
      const newScore = (avg ?? 100) - agg.missed * 5;
      if (newScore < curScore) studentePrioritario = candidate;
    });
    if (studentePrioritario) {
      const sevAvg = (studentePrioritario.avg ?? 100);
      if (sevAvg >= 70 && studentePrioritario.missed <= 1) {
        // not really at risk
        studentePrioritario = null;
      }
    }

    // ── Build cards ──
    const cards = buildCards({
      className,
      subject,
      avgScore,
      completionRatio,
      completionLabel,
      argomentoCritico,
      topErrors,
      nSegnaliEmotivi,
      totalStudents,
      activeStudents,
      classId,
      studentePrioritario,
    });

    // ── Legacy summary + suggestions (kept for retrocompat) ──
    const summary = topErrors.length > 0
      ? `${className} sta lavorando su ${subject}. Sono emerse alcune difficoltà ricorrenti su: ${topErrors.map(e => `"${e.topic}"`).join(", ")}. Inoltre ${completionLabel}.`
      : `${className} sta lavorando su ${subject}. Per ora non emergono difficoltà rilevanti e ${completionLabel}.`;
    const suggestions = topErrors.length > 0
      ? [
          `Dedica una breve attività di ripasso su "${topErrors[0].topic}" all'inizio della prossima lezione.`,
          "Forma piccoli gruppi misti dove gli studenti più sicuri spiegano ai compagni in difficoltà.",
        ]
      : ["Continua con il ritmo attuale, è equilibrato."];

    // ── Optional AI polish for card text ──
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    let aiCards: any = null;
    if (LOVABLE_API_KEY) {
      try {
        aiCards = await polishCardsWithAI(LOVABLE_API_KEY, cards, {
          className, subject, completionLabel, argomentoCritico, topErrors,
          nSegnaliEmotivi, totalStudents, activeStudents, studentePrioritario,
        });
      } catch (e) {
        console.error("AI polish failed, using deterministic cards:", e);
      }
    }

    const finalCards = {
      card1: { ...cards.card1, testo: aiCards?.card1?.testo || cards.card1.testo },
      card2: { ...cards.card2, testo: aiCards?.card2?.testo || cards.card2.testo },
      card3: { ...cards.card3, testo: aiCards?.card3?.testo || cards.card3.testo },
      card4: { ...cards.card4, testo: aiCards?.card4?.testo || cards.card4.testo },
    };

    return new Response(JSON.stringify({
      summary, suggestions,
      ...finalCards,
      source: aiCards ? "ai" : "deterministic",
    }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e) {
    console.error("class-learning-summary error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});

// ───────────────────── helpers ─────────────────────

function buildCards(ctx: any) {
  const {
    className, subject, avgScore, completionRatio, completionLabel,
    argomentoCritico, topErrors, nSegnaliEmotivi, totalStudents,
    activeStudents, classId, studentePrioritario,
  } = ctx;

  // CARD 1 — Apprendimento
  let testo1 = "";
  if (totalStudents === 0) {
    testo1 = `Nessuno studente è ancora iscritto a ${className}: condividi il codice classe per iniziare a vedere i dati di apprendimento.`;
  } else if (activeStudents === 0) {
    testo1 = `${className} è iscritta ma non ci sono ancora attività completate. Assegna una prima attività per vedere come la classe sta apprendendo ${subject}.`;
  } else if (argomentoCritico) {
    testo1 = `Su ${subject}, sta emergendo una difficoltà ricorrente su "${argomentoCritico}". ${completionLabel.charAt(0).toUpperCase() + completionLabel.slice(1)}. Vale la pena consolidare questo punto prima di andare avanti.`;
  } else if (avgScore != null && avgScore >= 70) {
    testo1 = `${className} sta procedendo bene su ${subject}: i risultati delle attività sono buoni e ${completionLabel}.`;
  } else {
    testo1 = `${className} sta lavorando su ${subject}. Per ora non emergono argomenti critici e ${completionLabel}.`;
  }

  // CARD 2 — Metodo
  let testo2 = "";
  if (!argomentoCritico) {
    testo2 = `Non ci sono ancora segnali che il metodo non stia passando: nessun argomento risulta problematico per più studenti contemporaneamente.`;
  } else if (topErrors[0]?.count >= 4) {
    testo2 = `"${argomentoCritico}" è un punto critico per più studenti insieme: probabilmente il canale spiegativo non sta passando come atteso. Vale la pena provare un esempio diverso o un supporto visivo.`;
  } else {
    testo2 = `"${argomentoCritico}" sta dando difficoltà a qualche studente, ma non in modo diffuso. Può essere utile riprenderlo brevemente con un esempio alternativo.`;
  }

  // CARD 3 — Clima
  let testo3 = "";
  if (totalStudents === 0) {
    testo3 = "Non ci sono ancora studenti iscritti per leggere il clima della classe.";
  } else if (nSegnaliEmotivi === 0) {
    testo3 = `Al momento non ci sono segnali di disagio aggregati. Se vuoi un quadro più ricco, un check-in di classe può aiutarti a leggere meglio il clima.`;
  } else if (nSegnaliEmotivi === 1) {
    testo3 = `C'è uno studente con un segnale aggregato di affaticamento emotivo. Niente di allarmante, ma un check-in di classe può aiutare a capire il momento.`;
  } else {
    testo3 = `Ci sono ${nSegnaliEmotivi} studenti con segnali aggregati di affaticamento emotivo nelle ultime due settimane. Un check-in di classe può aiutarti a leggere il clima senza esporre nessuno.`;
  }

  // CARD 4 — Studente prioritario
  let testo4 = "";
  let card4Cta: any = null;
  let card4CtaSec: any = null;
  if (!studentePrioritario) {
    testo4 = "Nessuno studente risulta in evidente difficoltà in questo momento — la classe procede in modo equilibrato.";
    card4Cta = {
      label: "Vedi tutti gli studenti",
      action: "open_classe_quadro",
      params: { classe_id: classId },
    };
  } else {
    const avgPart = studentePrioritario.avg != null
      ? `i suoi risultati sono sotto la media`
      : `non ha ancora svolto attività`;
    const missPart = studentePrioritario.missed > 0
      ? ` e ha lasciato indietro ${studentePrioritario.missed} attività`
      : "";
    testo4 = `${studentePrioritario.name}: ${avgPart}${missPart}. Conviene intervenire adesso prima che il distacco aumenti.`;
    card4Cta = {
      label: "Apri profilo",
      action: "open_studente",
      params: { studente_id: studentePrioritario.user_id, classe_id: classId },
    };
    card4CtaSec = {
      label: "Genera recupero",
      action: "open_materiali",
      params: { tipo: "recupero", studente_id: studentePrioritario.user_id, classe_id: classId },
    };
  }

  return {
    card1: {
      titolo: "Come sta andando l'apprendimento",
      testo: testo1,
      cta_primaria: argomentoCritico ? {
        label: "Genera esercizi di rinforzo",
        action: "open_materiali",
        params: { tipo: "recupero", argomento: argomentoCritico, classe_id: classId },
      } : {
        label: "Assegna una nuova attività",
        action: "open_materiali",
        params: { tipo: "esercizi", classe_id: classId },
      },
      cta_secondaria: argomentoCritico ? {
        label: "Vedi risultati attività",
        action: "open_classe_quadro",
        params: { classe_id: classId, sezione: "attivita_assegnate", filtro_argomento: argomentoCritico },
      } : null,
    },
    card2: {
      titolo: "Il metodo sta funzionando?",
      testo: testo2,
      cta_primaria: argomentoCritico ? {
        label: "Prepara spiegazione alternativa",
        action: "open_coach_docente",
        params: {
          prompt_precaricato: `Prepara una spiegazione alternativa di "${argomentoCritico}" con un esempio diverso e un supporto visivo per ${className}.`,
          argomento: argomentoCritico,
          classe_id: classId,
        },
      } : {
        label: "Apri il Coach docente",
        action: "open_coach_docente",
        params: { classe_id: classId },
      },
      cta_secondaria: argomentoCritico ? {
        label: "Genera materiale diverso",
        action: "open_materiali",
        params: { tipo: "esercizi", argomento: argomentoCritico, classe_id: classId },
      } : null,
    },
    card3: {
      titolo: "Clima della classe",
      testo: testo3,
      cta_primaria: {
        label: "Vedi quadro classe",
        action: "open_classe_quadro",
        params: { classe_id: classId, sezione: "clima" },
      },
      cta_secondaria: null,
    },
    card4: {
      titolo: "Chi ha bisogno di attenzione",
      testo: testo4,
      cta_primaria: card4Cta,
      cta_secondaria: card4CtaSec,
    },
  };
}

async function polishCardsWithAI(apiKey: string, deterministicCards: any, ctx: any) {
  const sys = `Sei il Coach AI di SarAI. Riscrivi i 4 testi di card per un docente, in italiano, max 3-4 righe ognuno, tono collegiale, MAI percentuali o termini tecnici (no "score", "rate", "%"). Mantieni il SIGNIFICATO dei testi forniti, migliorane solo lo stile. Mai inventare nomi o numeri non presenti.

PRINCIPIO DEL RICONOSCIMENTO obbligatorio: apri sempre con cosa la classe STA facendo, poi l'ostacolo, poi (implicitamente) verso un'azione. Mai aprire con un deficit ("X studenti non...").

Rispondi SOLO con JSON valido tramite la tool call.`;

  const usr = `Contesto:
- Classe: ${ctx.className}
- Materia: ${ctx.subject}
- Stato consegne: ${ctx.completionLabel}
- Argomento critico principale: ${ctx.argomentoCritico || "nessuno"}
- N. argomenti critici: ${ctx.topErrors.length}
- Studenti con segnali emotivi aggregati: ${ctx.nSegnaliEmotivi} su ${ctx.totalStudents}
- Studente prioritario: ${ctx.studentePrioritario ? ctx.studentePrioritario.name : "nessuno"}

Testi da migliorare (mantieni significato):
1) ${deterministicCards.card1.testo}
2) ${deterministicCards.card2.testo}
3) ${deterministicCards.card3.testo}
4) ${deterministicCards.card4.testo}`;

  const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      model: "google/gemini-2.5-flash",
      messages: [{ role: "system", content: sys }, { role: "user", content: usr }],
      tools: [{
        type: "function",
        function: {
          name: "polish_cards",
          description: "4 testi raffinati per le card del docente",
          parameters: {
            type: "object",
            properties: {
              card1: { type: "object", properties: { testo: { type: "string" } }, required: ["testo"] },
              card2: { type: "object", properties: { testo: { type: "string" } }, required: ["testo"] },
              card3: { type: "object", properties: { testo: { type: "string" } }, required: ["testo"] },
              card4: { type: "object", properties: { testo: { type: "string" } }, required: ["testo"] },
            },
            required: ["card1", "card2", "card3", "card4"],
            additionalProperties: false,
          },
        },
      }],
      tool_choice: { type: "function", function: { name: "polish_cards" } },
    }),
  });

  if (!res.ok) throw new Error(`AI ${res.status}`);
  const data = await res.json();
  const tc = data.choices?.[0]?.message?.tool_calls?.[0];
  if (!tc?.function?.arguments) return null;
  return JSON.parse(tc.function.arguments);
}
