
UPDATE teacher_materials SET content = E'## Verifica di Matematica — Frazioni\n\n**Nome:** ________________  **Classe:** ____  **Data:** ________________\n\n---\n\n### Parte A: Frazioni equivalenti\n\n#### Esercizio 1: Trova la frazione equivalente\nCompleta le seguenti uguaglianze:\n\n1. $\\frac{1}{2} = \\frac{?}{6}$\n2. $\\frac{2}{3} = \\frac{?}{9}$\n3. $\\frac{3}{4} = \\frac{?}{12}$\n4. $\\frac{5}{10} = \\frac{?}{2}$\n\n#### Esercizio 2: Vero o Falso\nIndica se le seguenti coppie sono frazioni equivalenti:\n\n1. $\\frac{2}{4}$ e $\\frac{1}{2}$ → ____\n2. $\\frac{3}{5}$ e $\\frac{6}{15}$ → ____\n3. $\\frac{4}{8}$ e $\\frac{1}{2}$ → ____\n\n---\n\n### Parte B: Operazioni con le frazioni\n\n#### Esercizio 3: Addizioni\nRisolvi le seguenti addizioni e **semplifica** il risultato:\n\n1. $\\frac{1}{4} + \\frac{2}{4} =$\n2. $\\frac{1}{3} + \\frac{1}{6} =$\n3. $\\frac{2}{5} + \\frac{1}{10} =$\n\n#### Esercizio 4: Problema\nMaria ha mangiato $\\frac{1}{4}$ di una torta e suo fratello ne ha mangiato $\\frac{2}{4}$. Quanta torta hanno mangiato **in tutto**? Quanta ne resta?\n\n---\n\n### SOLUZIONI\n\n- 1.1: $\\frac{3}{6}$\n- 1.2: $\\frac{6}{9}$\n- 1.3: $\\frac{9}{12}$\n- 1.4: $\\frac{1}{2}$\n- 2.1: Vero\n- 2.2: Falso\n- 2.3: Vero\n- 3.1: $\\frac{3}{4}$\n- 3.2: $\\frac{1}{2}$\n- 3.3: $\\frac{1}{2}$\n- 4: $\\frac{3}{4}$ mangiata, $\\frac{1}{4}$ resta'
WHERE id = '0700a988-133f-475c-b572-7f807db78bf7';

UPDATE teacher_materials SET content = E'## Esercizi di Ripasso — Divisioni\n\nRipassa le divisioni con i seguenti esercizi a difficoltà crescente.\n\n---\n\n### Livello 1: Divisioni semplici\n\n#### Calcola a mente\n\n1. $36 \\div 6 =$\n2. $48 \\div 8 =$\n3. $54 \\div 9 =$\n4. $72 \\div 8 =$\n5. $81 \\div 9 =$\n\n---\n\n### Livello 2: Divisioni con resto\n\n#### Trova quoziente e resto\n\n1. $29 \\div 4 =$ ____ resto ____\n2. $37 \\div 5 =$ ____ resto ____\n3. $50 \\div 7 =$ ____ resto ____\n4. $65 \\div 8 =$ ____ resto ____\n\n---\n\n### Livello 3: Problemi\n\n#### Problema 1\nUna maestra ha **45 pennarelli** da dividere tra **7 bambini**. Quanti ne riceve ciascuno? Quanti ne avanzano?\n\n#### Problema 2\nUn fiorista ha **84 rose** e vuole fare mazzi da **6 rose** ciascuno. Quanti mazzi può fare?\n\n$$84 \\div 6 = 14$$'
WHERE id = '9e85dae3-eb72-4938-b7e2-7a7a9f368782';

UPDATE teacher_materials SET content = E'## Il Ciclo dell''Acqua — Schema Riassuntivo\n\nL''acqua sulla Terra si muove attraverso **quattro fasi** principali.\n\n---\n\n### Le 4 fasi del ciclo\n\n#### 1. Evaporazione\nIl calore del Sole fa **evaporare** l''acqua da mari, fiumi e laghi. L''acqua liquida si trasforma in **vapore acqueo** e sale nell''atmosfera.\n\n#### 2. Condensazione\nIl vapore acqueo sale dove l''aria è più fredda. Si **condensa** in goccioline che formano le **nuvole**.\n\n#### 3. Precipitazione\nQuando le goccioline diventano troppo pesanti, cadono come:\n- **Pioggia** (sopra 0°C)\n- **Neve** (sotto 0°C)\n- **Grandine** (forti correnti ascendenti)\n\n#### 4. Raccolta\nL''acqua viene raccolta da:\n- Fiumi e laghi\n- Falde acquifere sotterranee\n- Mari e oceani\n\nDa qui il ciclo **ricomincia**!\n\n---\n\n### Domande di verifica\n\n1. Perché si chiama \"ciclo\" dell''acqua?\n2. Qual è il ruolo del Sole nel ciclo?\n3. Che differenza c''è tra evaporazione e condensazione?\n4. Dove finisce l''acqua dopo che piove?'
WHERE id = 'd5c6e7c5-6607-45ea-ba6d-f40fd299a73f';

UPDATE teacher_materials SET content = E'## Preparazione INVALSI — Problemi\n\nEsercitati con problemi simili alle prove INVALSI. Leggi con attenzione e **ragiona** prima di rispondere.\n\n---\n\n#### Problema 1: Il treno\nUn treno parte alle **8:45** e arriva alle **10:20**. Quanto dura il viaggio?\n\na) 1 ora e 25 minuti\nb) 1 ora e 35 minuti\nc) 2 ore e 25 minuti\nd) 1 ora e 45 minuti\n\n---\n\n#### Problema 2: La spesa\nMarta compra **3 quaderni** a €1,50 l''uno e **2 penne** a €0,80 l''una. Paga con €10.\n\nQuanto spende in tutto?\n\n$$3 \\times 1{,}50 + 2 \\times 0{,}80 = ?$$\n\nQuanto riceve di resto?\n\n---\n\n#### Problema 3: Le figurine\nLuca ha **124 figurine** e ne regala $\\frac{1}{4}$ a Marco. Quante figurine restano a Luca?\n\n$$124 - \\frac{124}{4} = 124 - 31 = 93$$\n\n---\n\n#### Problema 4: Il giardino\nUn giardino rettangolare ha il **lato lungo** di 12 m e il **lato corto** di 8 m. Calcola:\n\n1. Il **perimetro**\n2. L''**area**\n\n$$P = 2 \\times (12 + 8) = 40 \\text{ m}$$\n$$A = 12 \\times 8 = 96 \\text{ m}^2$$\n\n---\n\n### Risposte\n\n- Problema 1: **b)** 1 ora e 35 minuti\n- Problema 2: Spesa = €6,10 — Resto = €3,90\n- Problema 3: 93 figurine\n- Problema 4: P = 40 m, A = 96 m²'
WHERE id = 'ad030130-f35b-4d15-9f18-fa60c292c9a7';

UPDATE teacher_materials SET content = E'## Recupero Tabelline del 7, 8 e 9\n\nEsercizi di recupero per studenti con difficoltà sulle tabelline.\n\n---\n\n### Esercizio 1: Completa le tabelline\n\n#### Tabellina del 7\n\n1. $7 \\times 3 =$ ____\n2. $7 \\times 6 =$ ____\n3. $7 \\times 8 =$ ____\n4. $7 \\times 9 =$ ____\n\n#### Tabellina dell''8\n\n1. $8 \\times 4 =$ ____\n2. $8 \\times 7 =$ ____\n3. $8 \\times 8 =$ ____\n4. $8 \\times 9 =$ ____\n\n#### Tabellina del 9\n\n1. $9 \\times 3 =$ ____\n2. $9 \\times 6 =$ ____\n3. $9 \\times 7 =$ ____\n4. $9 \\times 9 =$ ____\n\n---\n\n### Esercizio 2: Trova il numero mancante\n\n1. $7 \\times$ ____ $= 42$\n2. $8 \\times$ ____ $= 64$\n3. $9 \\times$ ____ $= 81$\n4. $7 \\times$ ____ $= 63$\n5. $8 \\times$ ____ $= 56$\n6. $9 \\times$ ____ $= 54$\n\n---\n\n### Esercizio 3: Problemi veloci\n\n#### Problema A\nIn una classe ci sono **7 file** di banchi con **8 banchi** per fila. Quanti banchi in tutto?\n\n$$7 \\times 8 = ?$$\n\n#### Problema B\nUn pasticciere prepara **9 vassoi** con **9 biscotti** ciascuno. Quanti biscotti ha preparato?\n\n$$9 \\times 9 = ?$$'
WHERE id = '7bfd336c-18d2-49ac-b3cd-38c51d5c9b84';
